services:
  traq-ing:
    container_name: traq-ing
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '4173:4173'
      - '5000:5000'
    environment:
      - TRAQ_AUTH_CLIENT_ID=${TRAQ_AUTH_CLIENT_ID}
      - TRAQ_TOKEN=${TRAQ_TOKEN}
      - DATABASE_URL=postgressql://user:password@host.docker.internal:5432/traq_ing
